version: '3.4'

# Whenever possible use dynamic ports here and use fixed ports in docker-compose.override.yml

services:

  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
      - "8080"
  postgres:
    image: postgres:12.4
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "infojobs"
      POSTGRES_PASSWORD: "inf123sboj"
      POSTGRES_DB: "boijoffer"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

